# Generated by Django 5.0.1 on 2024-01-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('count', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='auto.autobrand')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(max_length=255, unique=True)),
                ('in_use', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='auto.autobrand')),
                ('model', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='auto.automodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=25, unique=True)),
                ('car', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='auto.auto')),
            ],
        ),
    ]
