# Generated by Django 5.0.1 on 2024-01-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_userauto_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauto',
            name='car',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto.auto'),
        ),
    ]
